export default [
  {
    id : 0,
    name : "나이키 코트 레거시 캔버스",
    price : 62100,
    like : false,
    img1 : "./images/shose/1-1.jpg",
    img2 : "./images/shose/1-2.jpg",
    img3 : "./images/shose/1-3.jpg",
    img4 : "./images/shose/1-4.jpg",
  },
  {
    id : 1,
    name : "나이키 와플 원 프리미엄",
    price : 129000,
    like : false,
    img1 : "./images/shose/2-1.jpg",
    img2 : "./images/shose/2-2.jpg",
    img3 : "./images/shose/2-3.jpg",
    img4 : "./images/shose/2-4.jpg",
  },
  {
    id : 2,
    name : "나이키 에어맥스 GENOME",
    price : 199000,
    like : false,
    img1 : "./images/shose/3-1.jpg",
    img2 : "./images/shose/3-2.jpg",
    img3 : "./images/shose/3-3.jpg",
    img4 : "./images/shose/3-4.jpg",
  },
  {
    id : 3,
    name : "나이키 레트로 GTS",
    price : 63200,
    like : false,
    img1 : "./images/shose/4-1.jpg",
    img2 : "./images/shose/4-2.jpg",
    img3 : "./images/shose/4-3.jpg",
    img4 : "./images/shose/4-4.jpg",
  },
  {
    id : 4,
    name : "나이키 챌린저 OG",
    price : 77400,
    like : false,
    img1 : "./images/shose/5-1.jpg",
    img2 : "./images/shose/5-2.jpg",
    img3 : "./images/shose/5-3.jpg",
    img4 : "./images/shose/5-4.jpg",
  },
  {
    id : 5,
    name : "나이키 에어맥스 인터락 라이트",
    price : 99000,
    like : false,
    img1 : "./images/shose/6-1.jpg",
    img2 : "./images/shose/6-2.jpg",
    img3 : "./images/shose/6-3.jpg",
    img4 : "./images/shose/6-4.jpg",
  },
  {
    id : 6,
    name : "나이키 와플 트레이너 2",
    price : 98100,
    like : false,
    img1 : "./images/shose/7-1.jpg",
    img2 : "./images/shose/7-2.jpg",
    img3 : "./images/shose/7-3.jpg",
    img4 : "./images/shose/7-4.jpg",
  },
  {
    id : 7,
    name : "나이키 데이브레이크",
    price : 77400,
    like : false,
    img1 : "./images/shose/8-1.jpg",
    img2 : "./images/shose/8-2.jpg",
    img3 : "./images/shose/8-3.jpg",
    img4 : "./images/shose/8-4.jpg",
  },
  {
    id : 8,
    name : "나이키 에어맥스 던",
    price : 129000,
    like : false,
    img1 : "./images/shose/9-1.jpg",
    img2 : "./images/shose/9-2.jpg",
    img3 : "./images/shose/9-3.jpg",
    img4 : "./images/shose/9-4.jpg",
  },
  {
    id : 9,
    name : "나이키 에어맥스 PRE-DAY",
    price : 159000,
    like : false,
    img1 : "./images/shose/10-1.jpg",
    img2 : "./images/shose/10-2.jpg",
    img3 : "./images/shose/10-3.jpg",
    img4 : "./images/shose/10-4.jpg",
  },
  {
    id : 10,
    name : "나이키 에어맥스 90 NRG",
    price : 169000,
    like : false,
    img1 : "./images/shose/11-1.jpg",
    img2 : "./images/shose/11-2.jpg",
    img3 : "./images/shose/11-3.jpg",
    img4 : "./images/shose/11-4.jpg",
  },
  {
    id : 11,
    name : "나이키 에어맥스 97 SE",
    price : 209000,
    like : false,
    img1 : "./images/shose/12-1.jpg",
    img2 : "./images/shose/12-2.jpg",
    img3 : "./images/shose/12-3.jpg",
    img4 : "./images/shose/12-4.jpg",
  }
] 